
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:dev@db:5432/tasks
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=tasks
    volumes:
      - tasks_data:/var/postgresql/data
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass dev
    volumes:
      - cache:/data
volumes:
  tasks_data:
  cache:
    driver: local